config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'articles#index'
get 'about', to: 'pages#about'
resources :articles
get 'signup', to: 'users#new'
resources :users, except: [:new]
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'
get 'edit', to: 'users#edit'
get 'users', to: 'users#index'

resources :articles do
  resources :comments
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	 has_many :comments, dependent: :destroy

 validates :title, presence: true, length:
  { minimum: 3, maximum: 50 }
 validates :description, presence: true, length:
  { minimum: 10, maximum: 500 }
validates :user_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

end

app/models/user.rb
class User < ActiveRecord::Base
	 has_many :articles
  has_secure_password


validates :username, presence: true, uniqueness: true, 
length: { minimum: 3, maximum: 30 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 105 }, 
uniqueness: { case_sensitive: false }, 
 format: { with: VALID_EMAIL_REGEX }
  before_save { self.email = email.downcase }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
helper_method :current_user, :logged_in?

def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
   !!current_user
end

def require_user
  if !logged_in?
    flash[:danger] = "Unknown user. Log in!"
    redirect_to root_path
   end
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def new
  @article = Article.new
end

def create
  @article = Article.new(article_params)
  @article.user = current_user
  if @article.save
   flash[:success] = "Article was successfully created"
   redirect_to article_path(@article)
  else
   render 'new'
  end
end

def show
end

def update
  if @article.update(article_params)
   flash[:success] = "Article was updated"
   redirect_to article_path(@article)
  else
   flash[:success] = "Article was not updated"
   render 'edit'
  end
end

def edit
end

def index
   @articles = Article.paginate(page: params[:page], per_page: 5)
  #@articles = Article.all
end

def destroy
  @article.destroy
  flash[:success] = "Article was deleted"
  redirect_to articles_path
end

private
  def article_params
   params.require(:article).permit(:title, :description)
  end
  def set_article
   @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end

def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 

	def index
 end

def about
end
 
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def  new
 end

 def create
   user = User.find_by(email: params[:session][:email].downcase)
 if user  && user.authenticate(params[:session][:password])
  session[:user_id] = user.id
  flash[:success] = "You have logged in"
  redirect_to users_path(user)
 else
  flash.now[:danger] = "There was something wrong with your login information"
  render 'new'
 end
 end

 def destroy
   def destroy
  session[:user_id] = nil
  flash[:success] = "You have logged out"
  redirect_to root_path
 end
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def has_secure_password
end

def new
@user = User.new
end

def create
  @user = User.new(user_params)
 if @user.save
  flash[:success] = "Welcome to the blog from Yanok #{@user.username}"
  redirect_to articles_path
 else
  render 'new'
 end
end

def edit
  @user = User.find(params[:id])
 end

 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
   flash[:success] = "Your account was updated successfully"
   redirect_to articles_path
  else
   render 'edit'
  end
 end

 def show
   @user = User.find(params[:id])
   @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
@users = User.paginate(page: params[:page], per_page: 5)
end




private
def user_params
  params.require(:user).permit(:username, :email, :password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     size = options[:size]
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    
     image_tag(gravatar_url, alt: user.username, class: "img-circle")
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Tell your story" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div><% end %>
 </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>


<%= render 'form' %>


 <%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div align = "center">
<h1 class = 'welcome'>Welcome to the Blog from Yanok</h1>


<h2>Everything we have...</h1>
</div>
<%= render 'shared/article', obj: @articles %>

<div align="center">
 <%= will_paginate %>
</div>



<div align = "center">
<%= link_to 'Back', articles_path,
class: "btn btn-primary btn-large" %>
</div>

app/views/articles/new.html.erb
<h1>Create your own article!</h1>




<%= render 'articles/form' %>


<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @article.user %>
 <ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
   </div>
  </div>
 </ul>
 <% end %>
 <h4 class="center description"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description) %>
 <div class="article-actions">

<%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-warning" %> |
<%= link_to 'Delete', article_path(@article), class: " btn btn-xs btn-danger",
method: :delete, data: {confirm: "Are you sure?",} %>|
<%= link_to 'Back', articles_path, class: "btn btn-xs btn-primary" %>
 
<h2>Comments</h2>

<%= render @article.comments %>
 


<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' },class: " btn btn-xs btn-danger" %>
</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Blog from Yanok", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul id = 'nav' class="nav navbar-nav">

       <li><%= link_to "Interesting Articles", articles_path %></li>


        <li><%= link_to "Create your own Article", new_article_path %></li>
       <li><%= link_to "All writers", users_path %></li>
<!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
-->

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

<% if logged_in? %>
  <li><%= link_to "Log out", logout_path, method: :delete %></li>
  <% else %>
  <li><%= link_to "Log in", login_path  %></li>
  <li><%= link_to "Sign up", signup_path %></li>
  <% end %>




      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogFromYanok</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/navigation' %>
   <%= render 'shared/messages' %>




    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About my Blog</h1>

<%= link_to 'About', about_path %>
<%= link_to 'Home', root_path %>
<%= link_to 'Back', articles_path %>

app/views/pages/index.html.erb
<h1>Welcome to the Blog from Yanok</h1>


<%= render 'shared/article', obj: @articles %>

<%= link_to 'Back', articles_path %>

app/views/pages/show.html.erb
<h1>Showing selected article</h1>
<p>
 Title: <%= @article.title %>
</p>
<p>
 Description: <%= @article.description %>
</p>



<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
 <div class="col-md-4 col-md-offset-5 center">
  <%= gravatar_for @user, size: 150 %>
 </div>
</div><h4 align="center"><%= @user.username %>'s articles</h4><%= render 'shared/article', obj: @user.articles %>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <div class="article-actions">
              <%= link_to 'Show', article_path(article), class: "btn btn-xs btn-warning" %> |
<% if logged_in?%>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
<% end%>

  <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prevent this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>
  <div class="form-group">


   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>

   <div>
     <%= link_to "Edit ", edit_path  %>
   </div>

  </div><% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
  </div>
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center">

 <% @users.each do |user| %>
  <ul class="listing">
   <div class="row">
    <div class="well col-md-4 col-md-offset-4">
     <li><%= link_to gravatar_for(user), user_path(user) %></li>
     <li class="article-title"><%= link_to user.username, user_path(user) %></li>
     <li><small>
<%= pluralize(user.articles.count, "article") if user.articles %>
</small></li>

<% if logged_in? %>
<!--
<%= link_to 'Edit profile', edit_path(1),
class: "btn btn-primary btn-large" %>
-->
<%end%>
    </div>
   </div>
  </ul>
 <% end %>


<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>


<%= render 'shared/errors', obj: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
 <div class="col-md-4 col-md-offset-4 center">
<%= gravatar_for @user, size: 200 %>
 </div>
</div>

<h4 align="center">
<%= @user.username %>'s articles</h4>

<%= render 'shared/article', obj: @user.articles %>



<% if logged_in?%>
  <div align="center">
     <%= link_to "Edit profile",{:controller => "users", :action => "edit" },class: 'btn btn-primary btn-large'%>
</div>
<%end%>




<div align="center">
 <%= will_paginate @user_articles %>
</div>